use_frameworks!

platform :ios, '9.0'

target 'ThirdProject_Example' do
  pod 'ThirdProject', :path => '../'

  target 'ThirdProject_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
